/**
 * RBAC permission keys (v1) — single source of truth.
 * Server/DB enforce; UI hides by permission.
 * settings.view / settings.profile.edit: everyone; rest gated by role.
 */
export const PERMISSIONS = [
  'org.read',
  'org.update',
  'org.members.invite',
  'org.members.remove',
  'org.members.role.assign',
  'org.switch',
  'billing.read',
  'billing.update',
  'billing.cancel',
  'walkthrough.create',
  'walkthrough.read',
  'walkthrough.update',
  'walkthrough.delete',
  'proposal.generate',
  'proposal.read',
  'proposal.send',
  'contract.create',
  'contract.read',
  'inspection.create',
  'inspection.read',
  'inspection.update',
  'inspection.complete',
  'inspection.score.read',
  'task.read.assigned',
  'task.read.all',
  'task.assign',
  'task.complete',
  'task.proof.upload',
  'issue.create',
  'issue.read',
  'issue.assign',
  'issue.close',
  'dashboard.sales',
  'dashboard.ops',
  'dashboard.exec',
  'settings.view',
  'settings.profile.edit',
  'settings.org.view',
  'settings.org.edit',
  'settings.billing.view',
  'settings.billing.manage',
  'settings.users.view',
  'settings.users.manage',
  'settings.roles.manage',
  'settings.integrations.manage',
  'settings.branding',
  'settings.integrations',
  'settings.ai',
  'maps.read',
  'maps.write',
  'lead.read',
  'lead.write',
  'lead.import',
  'lead.admin',
  'ops.read',
  'ops.write',
  'accounts.read',
  'accounts.write',
  'coverage.read',
  'coverage.write',
  'coverage.admin',
] as const;

export type PermissionKey = (typeof PERMISSIONS)[number];

/** Settings-specific keys for tab visibility and mutation gating. */
export const SETTINGS_PERMISSION_KEYS = [
  'settings.view',
  'settings.profile.edit',
  'settings.org.view',
  'settings.org.edit',
  'settings.billing.view',
  'settings.billing.manage',
  'settings.users.view',
  'settings.users.manage',
  'settings.roles.manage',
  'settings.integrations.manage',
] as const;
export type SettingsPermissionKey = (typeof SETTINGS_PERMISSION_KEYS)[number];
