'use client';

import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { formatDateTime } from '@/lib/utils';
import Image from 'next/image';

interface PublicReportViewProps {
  inspection: any;
  sections: any[];
  sectionScores: any[];
}

export function PublicReportView({ inspection, sections, sectionScores }: PublicReportViewProps) {
  return (
    <div className="min-h-screen bg-gray-50 py-8">
      <div className="max-w-4xl mx-auto px-4 space-y-6">
        <div className="text-center mb-8">
          <h1 className="text-3xl font-bold text-gray-900">Inspection Report</h1>
          <p className="text-gray-600 mt-2">{inspection.locations?.name}</p>
        </div>

        <Card>
          <CardHeader>
            <div className="flex items-center justify-between">
              <CardTitle>Summary</CardTitle>
              {inspection.total_score !== null && (
                <div className="text-3xl font-bold text-primary">
                  {inspection.total_score.toFixed(1)}%
                </div>
              )}
            </div>
          </CardHeader>
          <CardContent className="space-y-4">
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-gray-500">Template:</span>
                <span className="ml-2 font-medium">{inspection.templates?.name}</span>
              </div>
              <div>
                <span className="text-gray-500">Inspector:</span>
                <span className="ml-2 font-medium">{inspection.profiles?.full_name || 'Unknown'}</span>
              </div>
              <div>
                <span className="text-gray-500">Completed:</span>
                <span className="ml-2 font-medium">
                  {inspection.completed_at ? formatDateTime(inspection.completed_at) : 'In Progress'}
                </span>
              </div>
            </div>
          </CardContent>
        </Card>

        {sections.map((section) => {
          const sectionScore = sectionScores.find((s) => s.template_section_id === section.id);
          return (
            <Card key={section.id}>
              <CardHeader>
                <div className="flex items-center justify-between">
                  <CardTitle>{section.title}</CardTitle>
                  {sectionScore && (
                    <span className="text-lg font-semibold">{sectionScore.score.toFixed(1)}%</span>
                  )}
                </div>
              </CardHeader>
              <CardContent className="space-y-4">
                {section.template_items.map((item: any) => {
                  const response = item.inspection_responses?.[0];
                  const value = response?.value_json?.value;

                  return (
                    <div key={item.id} className="p-4 border rounded-lg">
                      <div className="flex items-start justify-between mb-2">
                        <div className="flex-1">
                          <h4 className="font-medium">{item.label}</h4>
                          {response?.notes && (
                            <p className="text-sm text-gray-600 mt-1">{response.notes}</p>
                          )}
                        </div>
                        <div className="text-right">
                          {value !== null && value !== undefined && (
                            <span className="text-sm font-medium">
                              {typeof value === 'boolean' ? (value ? 'Yes' : 'No') : String(value)}
                            </span>
                          )}
                        </div>
                      </div>
                      {item.inspection_photos && item.inspection_photos.length > 0 && (
                        <div className="flex gap-2 mt-3 flex-wrap">
                          {item.inspection_photos.map((photo: any, idx: number) => (
                            <div key={idx} className="relative w-32 h-32 border rounded">
                              <Image
                                src={photo.storage_path}
                                alt={`Photo ${idx + 1}`}
                                fill
                                className="object-cover rounded"
                              />
                            </div>
                          ))}
                        </div>
                      )}
                    </div>
                  );
                })}
              </CardContent>
            </Card>
          );
        })}

        <div className="text-center text-sm text-gray-500 py-4">
          Report generated by Janibear
        </div>
      </div>
    </div>
  );
}
